services:
  - type: cron
    name: chungkhoan-bot-sang
    runtime: python
    schedule: "0 1 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  - type: cron
    name: chungkhoan-bot-trua
    runtime: python
    schedule: "0 4 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  - type: cron
    name: chungkhoan-bot-chieu
    runtime: python
    schedule: "0 7 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
